### ISSUE TITLE
Modal css issue in ssr

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [tronghiep92/react-redux-modal-flex#1]
Hi,
having issues in ssr. not loading css.

**Comment by nghiepdev** [comment]
@nilaybrahmbhatt you can give me the example.

**Comment by nghiepdev** [comment]
@nilaybrahmbhatt Maybe fix in the new release v1.1.0
#2

**Comment by nilaybrahmbhatt** [comment]
@nghiepit  is this fixed?

**Comment by nghiepdev** [comment]
@nilaybrahmbhatt 
Yes, I'm testing on Next.js 7 and it works.
